name: Create the release pull request and release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-the-release-pull-request-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: depwatch
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
          enable-pep582: true
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish package
        run: |
          pdm config repository.pypi.username "__token__"
          pdm config repository.pypi.password ${{secrets.PYPI_TOKEN}}
          pdm publish
        if: ${{ steps.release.outputs.release_created }}
